apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: c82b4c-tools
  labels:
    app: clamav
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
      - name: clamav
        image: image-registry.openshift-image-registry.svc:5000/c82b4c-tools/clamav-prod@sha256:d6bf226eb34f7095c022e66d2882229f2eada38d515bc4c12a218253a2af920c
        imagePullPolicy: Always
        ports:
        - containerPort: 3310
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3310
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 3310
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 1100m
            memory: 2G
          requests:
            cpu: 100m
            memory: 500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
