apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"generation":1,"labels":{"app":"vhers-virus-scan"},"name":"vhers-virus-scan","namespace":"c82b4c-tools"},"spec":{"replicas":1,"selector":{"app":"vhers-virus-scan","deploymentconfig":"vhers-virus-scan"},"strategy":{"activeDeadlineSeconds":21600,"type":"Rolling"},"template":{"metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"},"labels":{"app":"vhers-virus-scan","deploymentconfig":"vhers-virus-scan"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","valueFrom":{"secretKeyRef":{"key":"app-db-hostname-prod","name":"patroni-ha-postgres-instance"}}},{"name":"DB_PORT","valueFrom":{"secretKeyRef":{"key":"app-db-port-prod","name":"patroni-ha-postgres-instance"}}},{"name":"DB_NAME","valueFrom":{"secretKeyRef":{"key":"app-db-name-prod","name":"patroni-ha-postgres-instance"}}},{"name":"DB_USERNAME","valueFrom":{"secretKeyRef":{"key":"app-db-username-prod","name":"patroni-ha-postgres-instance"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"app-db-password-prod","name":"patroni-ha-postgres-instance"}}}],"image":"vhers-virus-scan-tools:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"initialDelaySeconds":240,"periodSeconds":10,"successThreshold":1,"tcpSocket":{"port":3500},"timeoutSeconds":3},"name":"vhers-virus-scan","ports":[{"containerPort":3500,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"initialDelaySeconds":240,"periodSeconds":10,"successThreshold":1,"tcpSocket":{"port":3500},"timeoutSeconds":3},"resources":{"limits":{"cpu":"500m","memory":"2G"},"requests":{"cpu":"100m","memory":"500M"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"test":false,"triggers":[{"imageChangeParams":{"automatic":true,"containerNames":["vhers-virus-scan"],"from":{"from":null,"kind":"ImageStreamTag","name":"vhers-virus-scan-tools:latest"}},"type":"ImageChange"},{"type":"ConfigChange"}]}}
  creationTimestamp: "2023-12-06T18:59:56Z"
  generation: 40
  labels:
    app: vhers-virus-scan
  name: vhers-virus-scan
  namespace: c82b4c-tools
  resourceVersion: "12445889798"
  uid: b9d1eb2b-1c55-49b0-ae9a-892976df908b
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: vhers-virus-scan
    deploymentconfig: vhers-virus-scan
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: vhers-virus-scan
        deploymentconfig: vhers-virus-scan
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: app-db-hostname-prod
              name: patroni-ha-postgres-instance
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: app-db-port-prod
              name: patroni-ha-postgres-instance
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: app-db-name-prod
              name: patroni-ha-postgres-instance
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: app-db-username-prod
              name: patroni-ha-postgres-instance
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: app-db-password-prod
              name: patroni-ha-postgres-instance
        envFrom:
        - secretRef:
            name: vhers-virus-scan
        image: image-registry.openshift-image-registry.svc:5000/c82b4c-tools/vhers-virus-scan-tools@sha256:c86f55ecec7ec9f78c87235aac35b23fcae41ab240004ba0fda9ab44a9382f2e
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3500
          timeoutSeconds: 3
        name: vhers-virus-scan
        ports:
        - containerPort: 3500
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3500
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 2G
          requests:
            cpu: 100m
            memory: 500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - vhers-virus-scan
      from:
        kind: ImageStreamTag
        name: vhers-virus-scan-tools:latest
        namespace: c82b4c-tools
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/c82b4c-tools/vhers-virus-scan-tools@sha256:c86f55ecec7ec9f78c87235aac35b23fcae41ab240004ba0fda9ab44a9382f2e
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-02T20:52:00Z"
    lastUpdateTime: "2024-02-02T20:52:04Z"
    message: replication controller "vhers-virus-scan-22" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-03T21:39:56Z"
    lastUpdateTime: "2024-12-03T21:39:56Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: image-registry.openshift-image-registry.svc:5000/c82b4c-tools/vhers-virus-scan-tools@sha256:c86f55ecec7ec9f78c87235aac35b23fcae41ab240004ba0fda9ab44a9382f2e
      type: ImageChange
    message: image change
  latestVersion: 22
  observedGeneration: 40
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
