name: Run ZAP Full Scan

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        description: The Target URL
        options:
            - https://bc-emli-pin-mgmt-be-c82b4c-dev.apps.silver.devops.gov.bc.ca/
            - https://bc-emli-pin-mgmt-fe-c82b4c-dev.apps.silver.devops.gov.bc.ca/home

jobs:
  zap-scan:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
    
    steps:
    - uses: hmarr/debug-action@v3
    - uses: actions/checkout@v4
      with:
        ref: dev
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: ${{ github.event.inputs.url }}