name: Run ZAP Full Scan

on:
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write

    steps:
    - uses: hmarr/debug-action@v3
    - uses: actions/checkout@v4
      with:
        ref: dev
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: ${{ github.event.inputs.url }}